### ISSUE TITLE
Option to execute onLinkAdded() at most once per link, per onClock()

### ISSUE THREAD

**Issue by jschoete** [jbotsim/JBotSim#101]
I would like `onLinkAdded()` to be executed at most once per link, per `onClock()`. By default, it may be executed multiple times if nodes' movement during onClock() is significant. 

An option to switch between these two behaviours may be useful, since neither is the "better" behaviour.

**Comment by acasteigts** [comment]
Hi Jason, the default behavior is to update the links after each "event" (such as a movement), which indeed may create transient inconsistencies caused by in-round node movements. You can opt instead for a single update at the end of each round, by using `Topology.setRefreshMode(Topology.RefreshMode.CLOCKBASED)`. The default is `Topology.RefreshMode.EVENTBASED`.

**Comment by jschoete** [comment]
`Topology.setRefreshMode(Topology.RefreshMode.CLOCKBASED)` resolves this issue. Thanks!
