### ISSUE TITLE
Improve the quality of the default node icon

### ISSUE THREAD

**Issue by acasteigts** [jbotsim/JBotSim#42]

**Comment by remikey** [comment]
Applied:
* created 2 new 32x32 icons, instead of previous `circle.png` (16x16):
  * `circle-blue-ocean-32x32.png`
  * `circle-blue-32x32.png`
* `default-node-icon.png` is now a copy of `circle-blue-32x32.png`
* `Node.DEFAULT_ICON_SIZE` increased to `8`
* added dedicated example in `apps/examples/src/main/java/examples/basic/icons/`

**Comment by remikey** [comment]
Merged into `develop`.

**Comment by remikey** [comment]
***Update:*** after discussion, `Node.DEFAULT_ICON_SIZE` should be set to `10`.

**Comment by remikey** [comment]
Applied in https://github.com/jbotsim/JBotSim/commit/59f495fb9c195ad58bd000ce74c00406498f3996 and merged into `develop`.

**Comment by remikey** [comment]
Merged into `master`.
