### ISSUE TITLE
Message engine slower than it used to be

### ISSUE THREAD

**Issue by acasteigts** [jbotsim/JBotSim#85]
While running an example with a large number of nodes and links (about 3000 nodes of degree 50), we noticed that the message engine in the current version (1.1.1) is much slower than the one in version 1.0.0.

@remikey, could you please investigate and possibly fix this?

**Comment by remikey** [comment]
I confirm there was several things that could be improved here!
Among others, the way the `MessageEngine` used to check the existence of the link between the two nodes was slow.

Thereafter, a sum-up of my proposal.

## Main modifications

* `MessageEngine` is now an interface
  * A `reset()` method has been added.
  * It does not handle delays anymore.
   

* The former `MessageEngine` has been renamed to `DefaultMessageEngine` and modified. It:
   * Does not handle delays (see `DelayMessageEngine`)
   * Speeds-up former check on link existence

   
* A specific `DelayMessageEngine` has been re-created in `jbotsim-core`/`io.jbotsim.core`.
   * It handles delays better then the former `MessageEngine` used to:
     * by using a more direct implementation when the delay is *instantaneous*
     * using a HashMap which stores messages by indexing them using the moment they should be delivered
   * A new `DelayMessageEngine.disableLinksContinuityChecks()` method has been added. It prevents the system from checking the link's existence during intermediate rounds; speeding things up in static environment.
   * `AsyncMessageEngine` and `RandomMessageEngine` implementations have been modified to benefit from the new
   `DelayMessageEngine` capabilities.
     * test classes have been added to showcase all MessageEngines behaviors

* Note that any implementation which inherited from `MessageEngine` will have to make a choice:
  * inherit from `DefaultMessageEngine` (no delay feature)
  * inherit from `DelayMessageEngine` (has delay feature)
  * actually implement  the `MessageEngine` interface


* More user examples have been added in the `examples.features.messaging` package

* Testing:
  * `MessageEngineLoadTesting` has been added to specificaly test the 3000 / 50 case
 

## Side modifications

* `Node` class
  * `Node.hasNeighbor(Node)`, `Node.hasInNeighbor(Node)`, `Node.hasOutNeighbor(Node)` have been added
  * `Node.getOutNeighbors()` has been improved, avoiding unnecessary copies

* `Message` class
  * `Message.isRetryModeEnabled()` accessor has been added

**Comment by remikey** [comment]
My modifications are pushed on branch `fix/85-message-engine-slowed`.
Since this is a critical part of the system, it really needs to be reviewed. 
@acasteigts , @pictavien , could you please have a look?

**Comment by pictavien** [comment]
Hi @remikey,

Here's a first review.

**CHANGELOG.md**
   * line 23: "delays better *then* the former" -> *than*
   * line 26: "test classes have..." seems to be wrongly indented.
   * the item related to the transparent icon could be separated from paragraphs about message engines

**Message engine examples**
  * `AsyncMessageEngine{FIFO,NonFIFO}` examples miss the licence header.  
  * Except for FIFO case, perhaps could examples have the same parameters: dimension of the 
    grid, time-unit.
  * `AsyncMessageEngineFIFOExample.java`
    * what's the aim of following lines ?
     ```  
     messageEngine.setAverageDuration(500);
     messageEngine.setDelay(20); 
     ```
     `setDelay(20)` makes the call to `setAverageDuration(500)` useless. If it is done on purpose
     a small comment could help.
    * The file name could be suffixed with `Main` to be consistent with other examples.   

**MessageEngine.java**
  * Without more information, I doubt that some one could implement this interface without 
  a deep inspection of `DefaultMessageEngine`. Comments should precise available methods (from `Node.class` and 
  `Topology.class`) that must or should be used; e.g., `Node.onMessage()`. 
  * Does `setTopology()` reset something if it just assigns an instance member the interface could be 
  changed into an abstract class ? 
  * What is the purpose of `reset()` and when is it invoked ?
   
**DefaultMessageEngine.java**
  * Line 36: `If `*and*` {@link Message} can't be` -> *a*
  * We should improve performances using an ``HashSet`` containing existing nodes instead of a ``List`` as follows. 
    ```
    HashSet<Node> nodes = new HashSet<>();
    nodes.addAll(topology.getNodes());
    ```
    Perhaps a better way could be to allow ``topology.getNodes()`` to accept an allocated 
    ``Collection<Node>`` as parameter:
    ```
    public List<Node> getNodes() {
        List<Node> result = new ArrayList<>(nodes);
        getNodes(result);
        return result;
    }
      
    public void getNodes(Collection<Node> coll) {
        coll.addAll(nodes);      
    }  
    ```
  * `protected` API misses comments. For instance, it could be helpful to known that `collectMessage` methods 
    clear send queues.
  * Since `MessageListener`s are stored in the topology, perhaps we could add a `notifyDeliverMessage` method to 
    `Topology` instead of an explicit use of `topology.messageListeners`.
  
**DelayMessageEngine.java** 
  * `onClock()` duplicates code of `DefaultMessageEngine.onClock()`. Perhaps `DefaultMessageEngine` could have
  a protected method `filterDeliveredMessages` that, by default, returns all messages.
  * I'm wondering if this class couldn't be simpler using a `PriorityQueue` ?
     
**Node.java**
  * New predicates have been added: `boolean has{In,Out,}Neighbor(Node n)`.
    The implementation of `hasNeighbor(Node n)` in the case of undirected topologies checks if  
    both `hasInNeighbor(Node n)` AND `hasOutNeighbor(Node n)` return `true`. This suggests that existence of  
    of both links (in and out) are checked. However `hasInNeighbor(Node n)` simply calls `n.hasOutNeighbor(this)`
    which means that only one link is checked.

**RandomMessageEngine.java and AsyncMessageEngine.java**
  * I suggest to rename `RandomMessageEngine` into `RandomDelayMessageEngine` to clarify where the randomness is applied. One could think 
  of it as a lossy `MessageEngine`.
  * For both classes, I also suggest to add a mean to control the random number generation. Otherwise, it will be difficult
  to implement tests.
  * `AsyncMessageEngine` follows a `exponential` distribution to compute delays while `RandomMessageEngine` just  
  draw a random number less than the maximum delay. Perhaps, in the future, the `RandomDelayMessageEngine` could
  propose others distributions.  
  
**No load tests**
  * There is no load test. It could be useful to evaluate implementations of MessageEngines.

**Comment by remikey** [comment]
Thank you for the review @pictavien . I have applied most of the review.
I discuss thereafter the points that I have not, or with modifications. Please feel free to insist on issues you deem important, or that I might have forgotten.


   
**Message engine examples**
* Regarding FIFO examples, I have unified the examples (names, parameters, etc.), but I did not factorize them into `GenericMessageEngineExample` in order to keep them separated (only the `GridMessagingNode` remains in a separate file).

**DefaultMessageEngine.java**
* I have created Since `MessageListener`s are stored in the topology, perhaps we could add a `Topology.notifyMessageDelivered(Message)` and added a copy of the listeners list in order to avoid possible (yet unlikely) `ConcurrentModificationException`s, as in #56. 
  I have not noticed a significant slow-down when introducing this change, but it might be a good point to start if we later have such issues.
  
**DelayMessageEngine.java** 
  * Regarding `onClock`'s chuncks duplication, I had already tried and create something generic enough in `DefaultMessageEngine.onClock()` so that  `DelayMessageEngine` could benefit from it. Yet, everything I have thought of seemed very far fetched.

**RandomMessageEngine.java and AsyncMessageEngine.java**
  * I agree that it would be interesting to provide a way to control the randomness. Nevertheless, I think it is out of the scope of the present issue.

**MessageEngineLoadTesting.java**
  * I kept the `JViewer` on purpose. It was in an effort to keep things as close to the "real test" as possible, although it's does not look good.
  * It would be interesting to have load tests has you propose. Yet it is more complicated to implement and would really need to be thought about.

**MessageEngine.java**

* The interface's purpose is to enforce the existence its methods so that they can be called by their users. This is not the place to keep put those implementation-specific information. 

  I think a dedicated documentation describing the whole messaging/clock system should definitely exist.

  Going further, I think that few users will need to modify the message engine. Those who need will probably subclass one of the existing message engines. The very few who will try and implement `MessageEngine` will probably be developers who will first look at the rest of the source code.

**Comment by remikey** [comment]
My bad: now with code properly pushed, and CIed.
A big squash will be needed after your validation.

**Comment by remikey** [comment]
rebased over new `develop`

**Comment by pictavien** [comment]
Hi @remikey,

Thanks for the update.  I have made a quick review of the javadoc. Here are some typos before closing this issue. Regarding  remarks about `AsyncMessageEngineTest` below, I not sure they deserve a fix :) 


* CHANGELOG.md:55: a type "Node *is* in the" -> "Node in the" seems more correct, no ?
* MessageEngine.java
  * line 32: the documentation of `setTopology` refers to `DefaultMessageEngine` and not `MessageEngine`.
  * line 39: perhaps add a link to the `Scheduler` class.
* AsyncMessageEngine.java
  * line 41: The detail about `f(r)` could be preceded with something like: "The delay of delivery is drawn according to an exponential distribution law of rate 1./getAverageDuration()." (see https://en.wikipedia.org/wiki/Exponential_distribution)
  * line 225: The comment that refers to a `storable format`, and even the name of the method `prepareNewMessagesForStorage`, suggests that the list is translated in a `format` for some I/O operation. Actually messages are just gathered in a map w.r.t. to their delivery date...
* AsyncMessageEngineTest.java:
  * In `computeDelayFunction_minOk`, I think there exists a probability that the assertion is not satisfied, no ? 
  * In `computeDelayFunction_meansOk`, the error (delta) used to compare the computed mean and its expected value increases with `lambda` (take for instance 1000). This test will eventually fail for (much) greater values of `lambda`.

**Comment by remikey** [comment]
Thank you @pictavien . I think I have applied all your remarks.
Regarding `computeDelayFunction_minOk`: there is indeed a very small probability that the minimum value is not reached, but the 5000000 occurrences loop make this probability close enough to zero.

If it is ok for you, I will squash things as much as I can.

**Comment by pictavien** [comment]
Thanks ! It's ok for me.

**Comment by remikey** [comment]
Squashed the branch into something more concise.

**Comment by remikey** [comment]
merged into `develop`.
